// <auto-generated />
using BookStoreApp.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreApp.Api.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20240803115647_inital-migration")]
    partial class initalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreApp.Api.Models.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageID"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LanguageID");

                    b.HasIndex("LanguageName")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = 1,
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            LanguageID = 2,
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageID = 3,
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            LanguageID = 4,
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            LanguageID = 5,
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            LanguageID = 6,
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            LanguageID = 7,
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            LanguageID = 8,
                            LanguageName = "Punjabi"
                        },
                        new
                        {
                            LanguageID = 9,
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            LanguageID = 10,
                            LanguageName = "Bengali"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
